<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MainMenu.aspx.cs" Inherits="WeaponAndWizardry.MainMenu" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    
    <div style="background:url(../Content/Images/backgrounds/main_menu_bg.png) no-repeat; width: 100% 0;height:100% 0; background-position: right center; min-height:650px;">
        <div>
            <div class ="row center">
                <img alt="logo" longdesc="MA's Weapons&amp;Wizardry" src="Content/Images/ui/logo_3.png" style="width: 100%;" />
            </div>
        </div>
        <script src="https://code.createjs.com/createjs-2015.11.26.min.js"></script>
        <script>
          var soundID = "Thunder";

          function loadSound () {
            createjs.Sound.registerSound("stage2.mp3", soundID);
          }

          function playSound () {
            createjs.Sound.play(soundID);
          }

          function popup() {
              var generator = window.open('', 'name', 'height=400,width=500');
              str = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n';
              str += '<html lang="en">\n';
              str += '<head>\n';
              str += '<title>child<\/title>\n';
              str += '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n';
              str += '<link rel="stylesheet" href="style.css">\n';
              str += '<script type="text/javascript">window.onload=function() {opener.focus();};<\/script>\n';
              str += '<\/head>\n';
              str += '<body>\n';
              str += '<p>This page was generated by the main window.<\/p>\n';
              str += '<p><a href="" onclick="self.close(); return false;">Close<\/a> the popup.<\/p>\n';
              str += '<\/body>\n';
              str += '<\/html>';
              generator.document.write(str);
              generator.document.close();
          }

          setTimeout(function ()
          {
              sound = window.open("SoundPlayer.html", "name", "height=400,width=500");
              sound.blur();
          }, 1000);
        </script>
        <table style="width: 100%">
            <tr><td><div class="row"></div></td></tr>
            <tr><td><div class="row"></div></td></tr>
            <tr>
                <td style="width: 100%" align="center">
                    <asp:Button ID="Button_New_Game" CssClass="image_button_new" runat="server" Text="New Game" OnClick="Button_New_Game_Click"/>
                </td>
            </tr>
            <tr><td><div class="row"></div></td></tr>
            <tr>
                <td style="width: 100%" align="center">
                    <br />
                    <asp:Button ID="Button_Load_Game" CssClass="image_button_load" runat="server" Text="Load Game" OnClick="Button_Load_Game_Click"/>
                </td>
            </tr>
            <tr><td><div class="row"></div></td></tr>
            <tr>
                <td style="width: 100%" align="center">
                    <br />
                    <asp:Button ID="Button_Credits" CssClass="image_button_credits" runat="server" Text="Credits" OnClientClick="playSound(); return false;" class="playSound"/>
                </td>
            </tr>
            <tr><td><div class="row"><br /><br /><br /><br /><br /><br /><br /></div></td></tr>
        </table>
        
    </div>
</asp:Content>
